### ISSUE TITLE
There is no option to switch environment to production?

### ISSUE THREAD

**Issue by wisoot** [tangocard/raas-v2-sdk-php#5]
Looking at CatalogController which is tightly couple with RaasLib\Configuration class which hard coded static $environment to sandbox.

How can I change this to Production?

**Comment by arcdigital** [comment]
Hey, sorry I missed this. I believe you reached out via support ticket - but if not...you can set the environment by setting the environment variable on the config class:

`RaasLib\Configuration::$environment = RaasLib\Environments::PRODUCTION;`
